@startuml
'https://plantuml.com/object-diagram
class User

object LoginFragment
object RegisterFragment
object ViewProfile
object EditProfile{
String firstName
String lastName
String date
Boolean gender
String phoneNumber
String city
String writingOnMe
}

object RateTenant{
float stars
String feedback
}

object RenterMyAcceptedCars{
List<Car> cars
}

object RenterSpecificCarDetails{
user profile details
image car
List<Reviews> tenant
}

object RenterSearchCars{
List<Car> allCars
filtering method
}
object RenterAskForCar{
user profile details
image car
List<Reviews> tenant
}

User --> LoginFragment
LoginFragment --> RegisterFragment
LoginFragment --> RenterMyAcceptedCars

RenterMyAcceptedCars --> RenterSearchCars
RenterSearchCars --> RenterAskForCar

RenterMyAcceptedCars --> RenterSpecificCarDetails
RenterSpecificCarDetails --> RateTenant

RenterMyAcceptedCars --> ViewProfile
ViewProfile --> EditProfile
@enduml
